DROP DATABASE IF EXISTS UrbaPassDB;
CREATE DATABASE UrbaPassDB;
USE UrbaPassDB;

CREATE TABLE IF NOT EXISTS Direccion (
	uid CHAR(36) NOT NULL PRIMARY KEY COMMENT "",
    calle_principal VARCHAR(50) NOT NULL COMMENT "",
    calle_secundaria VARCHAR(50) NOT NULL COMMENT "",
    ciudad VARCHAR(25) NOT NULL COMMENT "",
    provincia VARCHAR(25) NOT NULL COMMENT "",
    pais VARCHAR(25) NOT NULL COMMENT ""
);

CREATE TABLE IF NOT EXISTS Persona (
	cedula CHAR(10) NOT NULL PRIMARY KEY COMMENT 'ID UNICO DE PERSONA',
    nombre VARCHAR(20) NOT NULL COMMENT 'NOMBRE DE LA PERSONA',
    apellido VARCHAR(20) NOT NULL COMMENT 'APELLIDO DEL PADRE DE LA PERSONA'
);

CREATE TABLE IF NOT EXISTS Urbanizacion (
	uid CHAR(36) NOT NULL PRIMARY KEY COMMENT "",
    nombre VARCHAR(30) NOT NULL UNIQUE COMMENT "",
    direccion CHAR(36) NOT NULL UNIQUE COMMENT "",
    ruc CHAR(13) NOT NULL UNIQUE COMMENT "",
    CONSTRAINT urbDirFK FOREIGN KEY (direccion) REFERENCES direccion (UID)
);

CREATE TABLE IF NOT EXISTS CuentaBancaria (
	uid CHAR(36) NOT NULL PRIMARY KEY COMMENT "",
    numero VARCHAR(14) NOT NULL COMMENT "",
    urbanizacion CHAR(36) NOT NULL COMMENT "",
    nombre_dueno VARCHAR(30) NOT NULL COMMENT "",
    nombre_banco VARCHAR(40) NOT NULL COMMENT "",
    CONSTRAINT ctaUrb FOREIGN KEY (urbanizacion) REFERENCES urbanizacion (uid)
);

CREATE TABLE IF NOT EXISTS Usuario (
	cedula CHAR(10) NOT NULL PRIMARY KEY COMMENT "",
    urbanizacion CHAR(36) NOT NULL COMMENT "",
    user VARCHAR(16) NOT NULL UNIQUE COMMENT "",
    correo VARCHAR(30) NOT NULL UNIQUE COMMENT "",
    clave VARCHAR(25) NOT NULL COMMENT "",
    CONSTRAINT usrUrbFK FOREIGN KEY (urbanizacion) REFERENCES urbanizacion (UID),
    CONSTRAINT usrCedFK FOREIGN KEY (cedula) REFERENCES Persona (cedula)
);

CREATE TABLE IF NOT EXISTS Residente (
	cedula CHAR(10) NOT NULL PRIMARY KEY COMMENT "",
    manzana CHAR(6) NOT NULL COMMENT "",
    villa CHAR(6) NOT NULL COMMENT "",
    CONSTRAINT manVil UNIQUE (manzana, villa),
    CONSTRAINT resCedFK FOREIGN KEY (cedula) REFERENCES Usuario (cedula)
);

CREATE TABLE IF NOT EXISTS Guardia (
	cedula CHAR(10) NOT NULL PRIMARY KEY COMMENT "",
    CONSTRAINT grdCedFK FOREIGN KEY (cedula) REFERENCES Usuario (cedula)
);

CREATE TABLE IF NOT EXISTS Administrador (
	cedula CHAR(10) NOT NULL PRIMARY KEY COMMENT "",
    CONSTRAINT admCedFK FOREIGN KEY (cedula) REFERENCES Usuario (cedula)
);

CREATE TABLE IF NOT EXISTS QR (
	uid CHAR(36) NOT NULL PRIMARY KEY COMMENT "",
    emisor CHAR(10) NOT NULL COMMENT "",
    visitante CHAR(10) NOT NULL COMMENT "",
    placa VARCHAR(7) NOT NULL COMMENT "",
    fechaEmision DATETIME NOT NULL COMMENT "",
    CONSTRAINT qrEmiFK FOREIGN KEY (emisor) REFERENCES residente (cedula),
    CONSTRAINT qrVisFK FOREIGN KEY (visitante) REFERENCES Persona (cedula)
);

CREATE TABLE IF NOT EXISTS Alicuota (
	uid CHAR(36) NOT NULL PRIMARY KEY COMMENT "",
    estado VARCHAR(15) DEFAULT "Sin Pagar" NOT NULL COMMENT "",
    valor FLOAT(8) COMMENT "",
    fecha_inicio DATE NOT NULL COMMENT "",
    residente CHAR(10) NOT NULL COMMENT "",
    CONSTRAINT aliResFK FOREIGN KEY (residente) REFERENCES residente (Cedula)
);

CREATE TABLE IF NOT EXISTS Pago (
	uid CHAR(36) NOT NULL PRIMARY KEY COMMENT "",
    alicuota CHAR(36) NOT NULL UNIQUE COMMENT "",
    valido BOOLEAN DEFAULT FALSE COMMENT "",
    image TEXT NOT NULL,
    fecha_pago DATE NOT NULL COMMENT "",
    CONSTRAINT pagAliFK FOREIGN KEY (alicuota) REFERENCES alicuota (UID)
);