DROP DATABASE IF EXISTS UrbaPassDB;
CREATE DATABASE UrbaPassDB;
USE UrbaPassDB;

CREATE TABLE IF NOT EXISTS Direccion (
	uid BINARY(16) NOT NULL PRIMARY KEY COMMENT "",
    calle_principal VARCHAR(50) NOT NULL COMMENT "",
    calle_secundaria VARCHAR(50) NOT NULL COMMENT "",
    ciudad VARCHAR(25) NOT NULL COMMENT "",
    provincia VARCHAR(25) NOT NULL COMMENT "",
    pais VARCHAR(25) NOT NULL COMMENT ""
);

CREATE TABLE IF NOT EXISTS Persona (
	cedula CHAR(10) NOT NULL PRIMARY KEY COMMENT 'ID UNICO DE PERSONA',
    nombre VARCHAR(20) NOT NULL COMMENT 'NOMBRE DE LA PERSONA',
    apellido VARCHAR(20) NOT NULL COMMENT 'APELLIDO DEL PADRE DE LA PERSONA'
);

CREATE TABLE IF NOT EXISTS Banco (
	uid BINARY(16) NOT NULL PRIMARY KEY COMMENT "",
    nombre VARCHAR(20) NOT NULL COMMENT ""
);

CREATE TABLE IF NOT EXISTS CuentaBancaria (
	uid BINARY(16) NOT NULL PRIMARY KEY COMMENT "",
    numero VARCHAR(14) NOT NULL COMMENT "",
    tipo BINARY(16) NOT NULL COMMENT "",
    CONSTRAINT cbtypeFK FOREIGN KEY (Tipo) REFERENCES Banco (UID)
);

CREATE TABLE IF NOT EXISTS Ruc (
	numero CHAR(13) NOT NULL PRIMARY KEY COMMENT ""
);

CREATE TABLE IF NOT EXISTS Urbanizacion (
	uid BINARY(16) NOT NULL PRIMARY KEY COMMENT "",
    nombre VARCHAR(30) NOT NULL UNIQUE COMMENT "",
    cuenta BINARY(16) NOT NULL UNIQUE COMMENT "",
    direccion BINARY(16) NOT NULL UNIQUE COMMENT "",
    ruc CHAR(13) NOT NULL UNIQUE COMMENT "",
    CONSTRAINT urbCtaFK FOREIGN KEY (Cuenta) REFERENCES CuentaBancaria (UID),
    CONSTRAINT urbDirFK FOREIGN KEY (Direccion) REFERENCES Direccion (UID),
    CONSTRAINT urbRucFK FOREIGN KEY (Ruc) REFERENCES Ruc (Numero)
);

CREATE TABLE IF NOT EXISTS Usuario (
	cedula CHAR(10) NOT NULL PRIMARY KEY COMMENT "",
    urbanizacion BINARY(16) NOT NULL COMMENT "",
    correo VARCHAR(30) NOT NULL UNIQUE COMMENT "",
    clave VARCHAR(25) NOT NULL COMMENT "",
    CONSTRAINT usrUrbFK FOREIGN KEY (Urbanizacion) REFERENCES Urbanizacion (UID),
    CONSTRAINT usrCedFK FOREIGN KEY (Cedula) REFERENCES Persona (Cedula)
);

CREATE TABLE IF NOT EXISTS Residente (
	cedula CHAR(10) NOT NULL PRIMARY KEY COMMENT "",
    direccion BINARY(16) NOT NULL COMMENT "",
    CONSTRAINT resDirFK FOREIGN KEY (Direccion) REFERENCES Direccion (UID),
    CONSTRAINT resCedFK FOREIGN KEY (Cedula) REFERENCES Persona (Cedula)
);

CREATE TABLE IF NOT EXISTS Guardia (
	cedula CHAR(10) NOT NULL PRIMARY KEY COMMENT "",
    CONSTRAINT grdCedFK FOREIGN KEY (Cedula) REFERENCES Persona (Cedula)
);

CREATE TABLE IF NOT EXISTS Administrador (
	cedula CHAR(10) NOT NULL PRIMARY KEY COMMENT "",
    CONSTRAINT admCedFK FOREIGN KEY (Cedula) REFERENCES Usuario (Cedula)
);

CREATE TABLE IF NOT EXISTS QR (
	uid BINARY(16) NOT NULL PRIMARY KEY COMMENT "",
    emisor CHAR(10) NOT NULL COMMENT "",
    visitante CHAR(10) NOT NULL COMMENT "",
    codigo VARCHAR(150) NOT NULL UNIQUE COMMENT "",
    placa VARCHAR(7) NOT NULL COMMENT "",
    CONSTRAINT qrEmiFK FOREIGN KEY (Emisor) REFERENCES Residente (Cedula),
    CONSTRAINT qrVisFK FOREIGN KEY (Visitante) REFERENCES Persona (Cedula)
);

CREATE TABLE IF NOT EXISTS Alicuota (
	uid BINARY(16) NOT NULL PRIMARY KEY COMMENT "",
    estado VARCHAR(10) NOT NULL COMMENT "",
    valor FLOAT(8) NOT NULL COMMENT "",
    fecha_inicio DATE NOT NULL COMMENT "",
    residente CHAR(10) NOT NULL COMMENT "",
    CONSTRAINT aliResFK FOREIGN KEY (Residente) REFERENCES Residente (Cedula)
);

CREATE TABLE IF NOT EXISTS Pago (
	uid BINARY(16) NOT NULL PRIMARY KEY COMMENT "",
    alicuota BINARY(16) NOT NULL UNIQUE COMMENT "",
    fecha_pago DATE NOT NULL COMMENT "",
    CONSTRAINT pagAliFK FOREIGN KEY (Alicuota) REFERENCES Alicuota (UID)
);
